travis: switch to Python 3 version
- remove dependence on python 2 brew tap
- install python3 on mac
- run test-run without specifying path to python
- create symbolic link to python3 on FreeBSD
- set --test-timeout --> 200 (DEBUG)
- use user install directory for Python modules

Installation of modules to a system directory is failed [1]:

ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/3.8'
Consider using the `--user` option or check the permissions.

To avoid this one should use option --user passed to pip.

1. https://gitlab.com/tarantool/tarantool/-/jobs/971934335

Part of #5652