iproto: support stacked diagnostics for errors
Introduced a new iproto message key IPROTO_ERROR_V2 to support
errors stacked diagnostics. This key extends iproto protocol
messages to have the following structure:
{
	// backward compatibility
	IPROTO_ERROR: "the most recent error message",
	// modern error message
        IPROTO_ERROR_V2: {
		{
			// the most recent error object
			"code": error_code_number,
			"reason": error_reason_string,
			"file": file_name_string,
			"line": line_number,
		},
		...
		{
			// the oldest (reason) error object
		},
	}
}

Such messages are decoded with updated netbox client and applier.
The legacy format with IPROTO_ERROR is kept to provide backward
compatibility in distributed environment.

Closes #1148